type Products {
  name: String
  category: String
  price: Float
  currency: String
  dimmentions: Dimmentions
  image: Image
  quantity: Int
  bestseller: Boolean
  featured: Boolean
  details: Details
  backorderLimit: Int
  backordered: Boolean
}

type Image @embedded {
  src: String
  alt: String
}

type Dimmentions @embedded {
  width: Int
  height: Int
}

type Details @embedded {
  dimmentions: Dimmentions
  size: Int
  description: String
  recommendation: Recommendation
}

type Recommendation @embedded {
  image: [Image]
}


type Query {
  allProducts: [Products!]
}
